name: Сборка и развёртывание на Production

on:
  push:
    branches:
      - master  # Измените на нужную вам ветку, из которой хотите запускать рабочий процесс

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование кода
        uses: actions/checkout@v2

      - name: Кэширование node_modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} # Используется package-lock.json для уникального ключа кэширования
      - name: Установка Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'  # Измените на нужную версию Node.js

      - name: Установка зависимостей
        run: npm install

      - name: Сборка Angular-приложения
        run: npm run build

      - name: Создание ветки production-build
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git checkout -b production-build
          git add .
          git commit -m "Production build from GitHub Actions"
          git push origin production-build

      - name: Развёртывание на ветке production-build
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: production-build
          publish_dir: ./dist/nab-english-testing  # Измените на директорию сборки вашего Angular-проекта
