name: Angular Build & Deploy

on:
  push:
    branches:
      - master # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Change this to your desired Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Project
        run: npm run build --prod

      # Add additional steps here if required, such as running tests or linting

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Change this to your desired Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Deploy to GitHub Pages
        run: npm install -g angular-cli-ghpages
        # Make sure your `angular.json` has the `outputPath` set to 'dist/your-project-name'
        # Replace 'your-project-name' with the actual name of your Angular project
        # Example: ng build --prod --output-path dist/your-project-name
        # Also, adjust the --base-href flag if your project is not hosted at the root of your repository
        # Example: ngh --dir=dist/your-project-name --base-href=/your-repo-name/

        # Below command assumes your main branch is 'main', change it if required
      - run: ngh --dir=dist/ --no-silent --branch=main

# Replace 'your-project-name' with the actual name of your Angular project
